### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by Fireman9** [Shadowrabbit/ModRimWorldFactionalWar#4]
Hi, I made a Russian translation for your mod, I didn't see the opportunity to make a pull request, so here's the translation.
[Russian.zip](https://github.com/Shadowrabbit/ModRimWorldFactionalWar/files/6840682/Russian.zip)

**Comment by Shadowrabbit** [comment]
It is today i saw this mail. sorry for late. thank you very much !


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Shadowrabbit/ModRimWorldFactionalWar"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月19日(星期一) 晚上8:19
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Shadowrabbit/ModRimWorldFactionalWar] Russian translation (#4)





 
Hi, I made a Russian translation for your mod, I didn't see the opportunity to make a pull request, so here's the translation.
 Russian.zip

**Comment by Shadowrabbit** [comment]
hi, could you post your steam url here? I want to add it to credit

**Comment by Fireman9** [comment]
https://steamcommunity.com/id/cyberfr0g/

**Comment by Shadowrabbit** [comment]
ty




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Shadowrabbit/FactionalWar"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月15日(星期三) 下午5:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Shadowrabbit/FactionalWar] Russian translation (#4)





 
https://steamcommunity.com/id/cyberfr0g/
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
